name = "GalaxyMNISTDatasets"
uuid = "139ca672-0216-40a0-b432-dd5568cb8d40"
authors = ["David MacMahon <davidm@astro.berkeley.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
